// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNh9bP7fR0muC8-tAH6YY57tZ1YAYddsI',
    appId: '1:639965968147:android:b7158031c614d52ce30ce6',
    messagingSenderId: '639965968147',
    projectId: 'intelligent-project-flow',
    storageBucket: 'intelligent-project-flow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiSXP7r5_qgPeOtpMS4S1nP-QwZ7bWZJ4',
    appId: '1:639965968147:ios:5075d0d6c435ef4ee30ce6',
    messagingSenderId: '639965968147',
    projectId: 'intelligent-project-flow',
    storageBucket: 'intelligent-project-flow.firebasestorage.app',
    iosBundleId: 'com.example.testMad',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHXDpHJhoF8yG-BuUnqIq9rzXpVmaxqFs',
    appId: '1:639965968147:web:470d62b967fe1ea1e30ce6',
    messagingSenderId: '639965968147',
    projectId: 'intelligent-project-flow',
    authDomain: 'intelligent-project-flow.firebaseapp.com',
    storageBucket: 'intelligent-project-flow.firebasestorage.app',
    measurementId: 'G-K4ZB22LCFX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiSXP7r5_qgPeOtpMS4S1nP-QwZ7bWZJ4',
    appId: '1:639965968147:ios:5075d0d6c435ef4ee30ce6',
    messagingSenderId: '639965968147',
    projectId: 'intelligent-project-flow',
    storageBucket: 'intelligent-project-flow.firebasestorage.app',
    iosBundleId: 'com.example.testMad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHXDpHJhoF8yG-BuUnqIq9rzXpVmaxqFs',
    appId: '1:639965968147:web:9a095a2b801f67dde30ce6',
    messagingSenderId: '639965968147',
    projectId: 'intelligent-project-flow',
    authDomain: 'intelligent-project-flow.firebaseapp.com',
    storageBucket: 'intelligent-project-flow.firebasestorage.app',
    measurementId: 'G-PQDN0PRSNH',
  );

}