// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment("ANDROID_FIREBASE_API_KEY"),
    appId: String.fromEnvironment("ANDROID_FIREBASE_API_ID"),
    messagingSenderId: '639965968147',
    projectId: 'flowiq',
    storageBucket: 'flowiq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '639965968147',
    projectId: '',
    storageBucket: 'flowiqw.firebasestorage.app',
    iosBundleId: 'com.example.testMad',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '639965968147',
    projectId: 'flowiq',
    authDomain: 'flowiq.firebaseapp.com',
    storageBucket: 'flowiq.firebasestorage.app',
    measurementId: 'G-K4ZB22LCFX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '639965968147',
    projectId: 'flowiqw',
    storageBucket: 'flowiq.firebasestorage.app',
    iosBundleId: 'com.example.testMad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '639965968147',
    projectId: 'flowiq',
    authDomain: 'flowiq.firebaseapp.com',
    storageBucket: 'flowiq.firebasestorage.app',
    measurementId: 'G-PQDN0PRSNH',
  );

}